#index:
#    path: /
#    controller: App\Controller\DefaultController::index
hello_page:
    path: /hello
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'hellopage.html.twig'